import GitBtn from "@components/GitBtn";
import Post from "@components/Post";

const YourPage = () => {

  return (
    <section className="max-w-7xl mx-auto relative">
      <div className="flex flex-col justify-center items-center">
        <h1 className="ubuntu_font text-[42px] text-center text-white">Paint Your imagination with <br className='max-md:hidden'/> <span className="text-[84px] head_text"> FOX HUES 
        </span></h1>
        <p className="mt-2 text-[#868e96] text-[14px] max-w-[600px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
        <h2 className="text-[#ccceda] text-[30px]">The Community Showcase</h2>
      </div>
      <GitBtn />
      <Post />
    </section>
  );
};

export default YourPage;
